create user tenant1 with password 'tenant1';
alter user tenant1 with createrole createdb;
create database tenant1;
alter database tenant1 owner to "tenant1";
create user tenant2 with password 'tenant2';
alter user tenant2 with createrole createdb;
create database tenant2;
alter database tenant2 owner to "tenant2";
create user tenant3 with password 'tenant3';
alter user tenant3 with createrole createdb;
create database tenant3;
alter database tenant3 owner to "tenant3";
create user tenant4 with password 'tenant4';
alter user tenant4 with createrole createdb;
create database tenant4;
alter database tenant4 owner to "tenant4";
create user tenant5 with password 'tenant5';
alter user tenant5 with createrole createdb;
create database tenant5;
alter database tenant5 owner to "tenant5";
create user tenant6 with password 'tenant6';
alter user tenant6 with createrole createdb;
create database tenant6;
alter database tenant6 owner to "tenant6";
